GET http://localhost:3000/

###
POST https://e-potli.onrender.com/createWallet
content-type: application/json

{
    "fname": "Ayush",
    "lname": "Addhyan",
    "email": "kryptonites.ju@gmail.com",
    "password": "AyushAddhyan",
    "phone": "9801254033" 
}

###
POST http://localhost:3000/createWallet
content-type: application/json

{
    "fname": "Ayush",
    "lname": "Addhyan",
    "email": "kryptonites.ju@gmail.com",
    "password": "AyushAddhyan",
    "phone": "9801254033" 
}